[COMMON]
SERVER_NAME = olympus_oxxer
; Adicionar/Disminuir horas para igualar el horario del servidor GMT-3
; Si es el mismo horario dejar vacio.
SERVER_TIME_DIFF = 1h

BUFFER_ID = 10002
GATEKEEPER_ID = 10001
MASTER_CLASS_ID = 10004

USE_BUFFER_BOOK = false
BUFFER_BOOK_ID = 13024


MODE_FARM = true
MODE_EVENT = true


NPC_SUBCLASS_PATH = Sub Class@Change subclass.

GM_NICKS = Admin@[ADM]@[GM]@[ADM]-HARRIS
SU_NICKS = dex

USE_DEBUG_MSG = true

USE_F12_ACTIVE_ANTICHEAT = true

USE_SOUND_GENERAL = false
USE_SOUND_EVENT_REGISTER = false

; Engine.SetTarget o el otro metodo mas rapido.
USE_SET_TARGET = false

; Las notificaciones solo se envian a uno de los servicio de mensajeria: Telegram o Discord
TELEGRAM_API = aa4c396fce350285f51ea14ddc805118


[AUTOLOGIN]
USE_AUTOLOGIN = true
PATH_L2_EXE = C:\Users\anton\Desktop\L2 OLYMPUS\Lineage2_Interlude 2\system\l2.exe
LOGIN_USER = frank758
LOGIN_PASS = chino123
CHAR_INDEX = 0


[HUNTER_PK]
USE_HUNTER_PK = false
HUNTER_WHITELIST_CLAN = 
HUNTER_WHITELIST_NICK = 
; opcional / use one key like F1, F2, 1, 2, q, w
HUNTER_PICKUP_KEY = F7
HUNTER_RADIO = 1800


[AUTOFARM]
VOICED_MENU = voiced_menu
VOICED_AUTOFARM = voiced_autofarm

VOICED_AUTOFARM_ON = voiced_enableAutoFarm
VOICED_AUTOFARM_OFF = voiced_enableAutoFarm

TEXT_AUTOFARM_ON = STARTED
TEXT_AUTOFARM_OFF = STOPPED

VOICED_AUTOFARM_RANGE_DEC = voiced_radiusAutoFarm dec_radius
VOICED_AUTOFARM_RANGE_INC = voiced_radiusAutoFarm inc_radius

VOICED_AUTOFARM_PAGE_DEC = voiced_pageAutoFarm dec_page
VOICED_AUTOFARM_PAGE_INC = voiced_pageAutoFarm inc_page

; Ex. = 1200 1000 600, Disable = 0
AUTOFARM_RANGE = 1000
; Ex. = 10 1, Disable = 0
AUTOFARM_PAGE = 10
; GB
VOICED_SET_AUTO_GB = 


; (1 second = 1000 ms / 15 seconds = 15000)
TO_VILLAGE_DELAY = 25000
TO_VILLAGE_DELAY_EXTRA = 5000

; delay aplicado despues de dar click en To Village, es el tiempo que le toma aparecer en la city
TO_VILLAGE_AFTER = 2000

; delay em ms para volver a iniciar un farm.
; delay random adicional al anterior.
FARM_AGAIN_DELAY = 10000
FARM_AGAIN_DELAY_EXTRA = 5000


; Apply this RANDOM DELAY in SECONDS after events like PvP/Tour/SoloBoss and TvT/Ktb/Ctf/Fos
AFTER_EVENT_DELAY_SEC = 20

; numero de veces que ira  farmear 
NUMERO_DE_CICLOS = 99999   

USE_SERVER_AUTOFARM = true
USE_ADRENALINE_AUTOFARM = false
USE_MY_AUTOFARM = false


[TELEPORT_SETTINGS]
; use bypass for dialogs
USE_BYPASS = true

USE_EXECUTE_BYPASS = false

; use Alt+B
USE_ALT_B = false

; Goddard
; TP_AUX_BYPASS = vipgoto 12005

; use book for teleport ?
USE_BOOK_ITEM = false
BOOK_ID = 5588

; Use other city for start, this help for evade stuck in giran.
USE_PROXY_CITY = true
USE_PROXY_ONLY_FOR_BUFF = true
PROXY_PATH = Goddard

; rtTown, rtClanHall, rtCastle, rtFort, rtFlags
RES_TYPE = rtFlags

; soe
USE_SCROLL_OF_SCAPE_CLAN_HALL = false
SCROLL_OF_SCAPE_CLAN_HALL_ID = 1829

USE_SCROLL_OF_SCAPE_GIRAN = false
SCROLL_OF_SCAPE_GIRAN_ID = 7126

USE_SCROLL_OF_SCAPE = false
SCROLL_OF_SCAPE_ID = 736

USE_UNSTUCK = true

SOE_EXTRA_DELAY = 8

USE_SOE_AFTER_DEAD = false


[FARM_SETTINGS]
; determina el spot para iniciar (20 parametros)
START_SPOT = 1
; muertes por spot
DEATHS_BY_SPOT = 1

; arcane power / vicous stance
USE_ARCANE_POWER = true

USE_MP_POTION = true
MP_POTION_NAME = Mana Potion
MP_POTION_PERCENTAGE = 65

USE_HP_POTION = true
HP_POTION_NAME = Major Healing Potion
HP_POTION_PERCENTAGE = 90

USE_CP_POTION = false
CP_POTION_NAME = Greater CP Potion
CP_POTION_PERCENTAGE = 85


; ONE_TIME_BYPASS = voiced_enableAntiKs@voiced_setBuffPrevent@voiced_LAssassin
; ONE_TIME_BYPASS = voiced_autofarm@[+]voiced_enableAntiKs@[+]enableSummonAttack
; ONE_TIME_BYPASS = voiced_menu@[+]voiced_hideEnchantGlow@[+]voiced_hideSkinsTextures@[+]voiced_hideWpSkinsTextures
; ONE_TIME_BYPASS = voiced_setPage 10@[+]voiced_enableAntiKs@[+]voiced_setTargetMode MONSTERS@[+]voiced_setTargetRange SHORT
ONE_TIME_BYPASS = voiced_autofarm@[+]voiced_enableAntiKs


; Show/Hide window options
; HIDE the window AFTER login
HIDE_GAME_WINDOW = false
; SHOW window to make To Village, then HIDE again.
SHOW_GAME_WINDOW_FOR_TO_VILLAGE = false

; Use when only can farm with 1 HWID
; When first char take 1 spot, the secondary char will be close cliente.
; use secondary char with objetive kill bots/chars/cleanSpots or farm quest quest
USE_DUALBOX_RESET = false
; Nick in Account list of adrenaline. the client will be force-close.
DUALBOX_RESET_NICK = 
DUALBOX_RESET_USE_SOE = false
DUALBOX_RESET_USE_GAMECLOSE = false


-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[TVT]
TVT = true
TVT_COMMAND = .tvtjoin

; Team vs Team: Teleport in x second(s)
TVT_TELEPORT_IN = 4

; Team vs Team: Fight start in x second(s)
TVT_EVENT_START_IN = 10

; x second(s) until the event is finished
TVT_EVENT_FINISH_IN = 285
; Teleporting back to town in x second(s)
TVT_TELEPORT_BACK_TO_TOWN_IN = 20

TVT_USE_TARGET_ATTACKABLE = false

; line
TVT_USE_TARGET_LINE_AB = false
TVT_LINE_AB_POINTS = 
tvt.baium.lineAB(115784, 14328, 10080);
tvt.baium.lineAB(113384, 17832, 10072);

; autofarm
TVT_USE_SERVER_AUTOFARM = false
TVT_AUTOFARM_BYPASSES = 

; teams
TVT_USE_TARGET_NAME = true
TVT_USE_TARGET_TITLE = false

TVT_MESSAGES_REGISTRATION_FIRST = Team vs Team@Joinable in Giran
TVT_MESSAGES_REGISTRATION = Team vs Team@reg
TVT_MESSAGES_START = Team vs Team@reg@ 5 second

TVT_METHOD = V3

; Mutiples coordenadas xyz
TVT_EVENT_CENTER = 
tvt.baium.center(114504, 15960, 10080);
tvt.bandit.center(83112, -16552, -1888);
now.ctf.center(4660, 149528, -2894);
now.tvt.tezza.center(174248, -88041, -5117);
Engine.MoveTo(149391, 46867, -3415);
olympus.tvt.center.field.of.wisper(81064, 209448, -3696);
olympus.tvt.center.field.of.wisper(78616, 210440, -3760);


-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[KTB]
KTB = false

KTB_COMMAND = .ktbjoin

KTB_RAID_XYZ = Engine.MoveTo(-84600, 253400, -3712);

; Teleporting in x second(s)
KTB_TELEPORT_IN = 15

; [Kill The Boss] Boss spawn in x second(s)
KTB_EVENT_START_IN = 5

; Teleporting back to town in x second(s)
KTB_TELEPORT_BACK_TO_TOWN_IN = 30

; Registrations for event: KTB have been opened
KTB_MESSAGES_REGISTRATION_FIRST = Kill The Boss@Joinable in Giran
KTB_MESSAGES_REGISTRATION = Kill The Boss@reg
KTB_MESSAGES_START = Kill The Boss@reg@ 5 second


-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[CTF]
CTF = false
CTF_COMMAND = .ctfjoin
CTF_TELEPORT_IN = 5
CTF_EVENT_START_IN = 10
CTF_EVENT_FINISH_IN = 290
CTF_TELEPORT_BACK_TO_TOWN_IN = 20
CTF_MESSAGES_REGISTRATION = CTF Event@reg
CTF_MESSAGES_START = CTF Event@reg@ 5 second


[FOS]
FOS = false
FOS_COMMAND = .join
FOS_TELEPORT_IN = 5
FOS_EVENT_START_IN = 10
FOS_EVENT_FINISH_IN = 290
FOS_TELEPORT_BACK_TO_TOWN_IN = 20
FOS_MESSAGES_REGISTRATION = Fortress Event@reg@5 minute
FOS_MESSAGES_START = Fortress Event@reg@ 5 second


-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[SOLO BOSS]
SOLO_BOSS = false
SOLO_BOSS_TELEPORT_PATH = Event Zone@ZONE 2

SOLO_BOSS_DEFAULT_BEFORE = 4m
SOLO_BOSS_DEFAULT_END = 2m

; la hora en que nace el primer raid solo 
;{start|before|end}
SOLO_BOSS_SCHEDULE = 10:50 @ 17:35 @ 21:05

;{ Solo boss path for each raid }
SOLO_BOSS_PATH_1 = Engine.MoveTo(-43640, 209208, -3344, 60);Engine.MoveTo(-43112, 210360, -3328, 60);Engine.MoveTo(-42440, 211528, -3552, 70);Engine.MoveTo(-40968, 213160, -3736, 100);Engine.MoveTo(-39880, 213960, -3736, 100);Engine.MoveTo(-38968, 214104, -3736, 80);
SOLO_BOSS_PATH_2 = Engine.MoveTo(-41016, 215912, -3736, 100);
SOLO_BOSS_PATH_3 = Engine.MoveTo(-40488, 215112, -3736, 100);
SOLO_BOSS_PATH_4 = 

SOLO_BOSS_PATH_5 = 
SOLO_BOSS_PATH_6 = 
SOLO_BOSS_PATH_7 = 
SOLO_BOSS_PATH_8 = 

SOLO_BOSS_PATH_9 = 
SOLO_BOSS_PATH_10 =

SOLO_BOSS_USE_PICKUP = false

; When have many NPC near, can set the NPC ID (@ separator)
SOLO_BOSS_NPC_IDS = 24010

; chest ID after raid dead
SOLO_BOSS_CHEST_ID = 


-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[PVP]
PVP_EVENT = true

PVP_EVENT_USE_CP = true

PVP_EVENT_CENTERS = 
a.camp
Engine.MoveTo(-55160, 141640, -2592, 15000, 1000);
Engine.MoveTo(-55256, 138136, -2912, 15000, 1000);
Engine.MoveTo(-49736, 141768, -2888, 15000, 1000);
olympus.pvp
pi(5016, -9688, -3776, 15000, 1500);
pi(5288, -15512, -3608, 15000, 1500);
pi(6392, -18712, -3720, 15000, 1500);
pi(4472, -8840, -3592, 15000, 1500);
pi(8632, -22856, -3736, 15000, 1500);


; 103 sps / 94 Archmage / 95 soultaker / 110 storm screamer
; 113 titan / 114 gk / 88 duelist / 
; 92 sagi / 93 adventurer
; PVP_EVENT_CLASS_ID = 102
PVP_EVENT_CLASS_ID = 95

PVP_EVENT_TELEPORT_PATH = PvP - Event@PvP Event 

PVP_EVENT_DEFAULT_BEFORE = 1m 20s
PVP_EVENT_DEFAULT_END = 15m

;{start|before|end}
PVP_EVENT_SCHEDULE = 11:30 @ 15:20 @ 18:30 @ 23:40

PVP_EVENT_USE_GK_TO_LEAVE_ZONE = false

; use for mage/archer
PVP_USE_MOVE_SPAWN = true
PVP_MOVE_SPAWN_DIST = 300
PVP_MOVE_SPAWN_TIME_MS = 1400

; extra delay for to village, default 0
PVP_TO_VILLAGE_EXTRA_DELAY_SECONDS = 0

PVP_AGGRESSIVE_PLAYERS_FIRST = false
; avoid targeting the following classes (@ separator)
PVP_IGNORE_CLASSES = 

; rtTown, rtClanHall, rtCastle, rtFort, rtFlags
PVP_RES_TYPE = rtTown
PVP_RES_TYPE_LEAVE_ZONE = rtFlags
PVP_USE_NOBLESSE = false
PVP_NO_ACTIVITY_COMMANDS = 

; tyrant: puma @ ogre @ hawk @ bear @ soul breaker @ force burst @ force blaster
; sps: solar @ ice vortex @ light vortex
; PVP_SKILL_LIST = hawk @ soul breaker @ force burst 
; PVP_SKILL_LIST = hawk @ force burst 
; PVP_SKILL_LIST = bear @ force burst @ force storm @ force blaster @ burning fist @ soul breaker
PVP_SKILL_LIST = surrender @ solar flare

; autofarm
PVP_USE_SERVER_AUTOFARM = false
PVP_AUTOFARM_BYPASSES = 

PVP_ZMAP =

PVP_USE_ADD_FRIEND = false
PVP_OID_FRIENDS = 





-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[TOUR]
TOUR_EVENT = false
TOUR_EVENT_CENTER = olympus(-20792, -21176, -3024);

TOUR_EVENT_RANGE = 3000
TOUR_EVENT_ZLIMIT = 250

TOUR_EVENT_NPC_ID = 32027

TOUR_REGISTER_PATH = Tournament Arenas@T1V1@Register
TOUR_UNREGISTER_PATH = remove

; 93 adventurer; 94 sorcer  103 sps
; 114 GK / 88 duelist
TOUR_CLASS_ID = 95
TOUR_EVENT_TELEPORT_PATH = Event Zone@Tournament

TOUR_EVENT_DEFAULT_BEFORE = 1s
TOUR_EVENT_DEFAULT_END = 30m

;start|before|end
TOUR_EVENT_SCHEDULE = 12:40 @ 16:40 @ 20:00 @ 22:25

TOUR_USE_SUMMON_CP = false

; if have agation or pet
TOUR_HAVE_AGATION_PET = true



-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[EVENT ZONE A]
USE = false
TAG = RUSH
DEFAULT_BEFORE = 20s
DEFAULT_END = 15m
USE_SERVER_TIME = true
SCHEDULE = 01:35 @ 03:35 

[EVENT ZONE B]
USE = false
TAG = AOE
DEFAULT_BEFORE = 1s
DEFAULT_END = 30m
USE_SERVER_TIME = true
SCHEDULE = 0:25


[EVENT ZONE C]
USE = false
TAG = ZONE3
DEFAULT_BEFORE = 40s
DEFAULT_END = 2m 30s
USE_SERVER_TIME = true
SCHEDULE = 20:05

[EVENT ZONE D]
USE = false
TAG = DUNGEON
DEFAULT_BEFORE = 10s
DEFAULT_END = 45m
USE_SERVER_TIME = true
SCHEDULE = 2:00

[EVENT ZONE E]
USE = false
TAG = DUNGEON
DEFAULT_BEFORE = 1s
DEFAULT_END = 30m 30s
USE_SERVER_TIME = true
SCHEDULE = 9:10 @ 11:10



-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[MISSION]
MISSION = true
MISSION_VOICED = voiced_mission
MISSION_COMPLETED_TEXT_1 = <font color="00FF00">
MISSION_COMPLETED_TEXT_2 = >Completed<
MISSION_LIST_VOICED = voiced_tvt_mission@voiced_tvt_mission_reward@voiced_farm_mission@voiced_farm_mission_reward@voiced_champion_mission@voiced_champion_mission_reward@voiced_pvp_mission@voiced_pvp_mission_reward@voiced_tournament_mission@voiced_tournament_mission_reward


-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[SUBCLASS 1]
CLASS_ID = 103
CLASS_NAME = Mystic Muse
BUFF_PATH = *@Scheme@MAGO@*@Recovery
ITEMS_SKILL = 
ARRAY_EQUIPMENT_ID =
USE_LOAD_GEAR = false

[SUBCLASS 2]
CLASS_ID = 95
CLASS_NAME = Soultaker
BUFF_PATH = *@Scheme@MAGO@*@Recovery
ITEMS_SKILL = 
ARRAY_EQUIPMENT_ID =
USE_LOAD_GEAR = false

[SUBCLASS 3]
CLASS_ID = 110
CLASS_NAME = Storm Screamer
BUFF_PATH = *@Scheme@MAGO@*@Recovery
ITEMS_SKILL = 
ARRAY_EQUIPMENT_ID =
USE_LOAD_GEAR = false



[SUBCLASS 4]
CLASS_ID = 93
CLASS_NAME = Adventurer
BUFF_PATH = *@Scheme@dagger@*@heal
ITEMS_SKILL = 
ARRAY_EQUIPMENT_ID =
USE_LOAD_GEAR = false

[SUBCLASS 5]
CLASS_ID = 113
CLASS_NAME = Titan
BUFF_PATH = *@Cancel@Scheme@Titan@*
ITEMS_SKILL = 
ARRAY_EQUIPMENT_ID =
USE_LOAD_GEAR = false

[SUBCLASS 6]
CLASS_ID = 88
CLASS_NAME = Duelist
BUFF_PATH = *@Scheme@duelist@*@Restore
ITEMS_SKILL =
ARRAY_EQUIPMENT_ID =
USE_LOAD_GEAR = false

[SUBCLASS 7]
CLASS_ID = 114
CLASS_NAME = Grand Khauatari
BUFF_PATH = *@Scheme@GK@*@Restore
ITEMS_SKILL = 10527
ARRAY_EQUIPMENT_ID =
; ARRAY_EQUIPMENT_ID =
USE_LOAD_GEAR = false

[SUBCLASS 8]
CLASS_ID = 92
CLASS_NAME = Sagittarius
BUFF_PATH = *@Warrior@Song@Renewal
ITEMS_SKILL = 10527
ARRAY_EQUIPMENT_ID =
USE_LOAD_GEAR = false


[SUBCLASS 9]
CLASS_ID = 102
CLASS_NAME = Moonlight Sentinel
BUFF_PATH = *@Warrior@Song@Renewal
ITEMS_SKILL = 10527
ARRAY_EQUIPMENT_ID =
USE_LOAD_GEAR = false

[SUBCLASS 10]
[SUBCLASS 11]
[SUBCLASS 12]






-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[SPOT DEFAULT]
TAG = DEFAULT
NAME = (default)
SUBCLASS_ID = 110
FORCE_REBUFF = true
BACK_TO_LAST_POSITION = true
BACK_TO_POSITION_RANGE = 150
USE_CHAR_PARADO = true
EXTRA_BYPASS = 

AUTOFARM_RANGE = 1000
AUTOFARM_PAGE = 10

USE_FAST_SKILL = true
FAST_SKILL_DELAY_MS = 150

USE_SURRENDER = false
USE_CORPSE_LIFE_DRAIN = false
USE_AOE = false
USE_PET = false
BTM_FROM_HP = 900
; BTM_FROM_HP = 0
USE_REPEAT_TP = false

; pathGatekeeper = 
; pathPoints = 

USE_GPS = false
GPS_FILENAME = 

; MyAutoFarm Settings
USE_HUNT_PLAYER_PVP = false
HUNT_RADIO = 1200

USE_PROTECT_FROM_PVP_PK = false


COMMANDS_BEFORE_BUFF = 
COMMANDS_AFTER_BUFF = 


-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

; How to create SPOTS
; https://youtu.be/hh_ua0NzCIg?si=cFdvPsLkxKoU1xyz

-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

; Red

[SPOT 13]
TAG = FARM
NAME = 
PATH_GATEKEEPER = Farm@Ruins 1
PATH_POINTS = 
Engine.MoveTo(95704, -114664, -3512, 80);
Engine.MoveTo(94952, -115416, -3560, 80);
Engine.MoveTo(93704, -115944, -3792, 80); base
Engine.MoveTo(92024, -116776, -3952, 60);
Engine.MoveTo(91304, -117816, -3896, 60);spot


[SPOT 14]
TAG = FARM
NAME = 
PATH_GATEKEEPER = Farm@Ruins 1
PATH_POINTS = 
Engine.MoveTo(95704, -114664, -3512, 80);
Engine.MoveTo(94952, -115416, -3560, 80);
Engine.MoveTo(93704, -115944, -3792, 80); base
Engine.MoveTo(91096, -117368, -3928, 60);
Engine.MoveTo(89464, -117944, -3752, 60); spot


-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

; Blue

[SPOT 21]
TAG = FARM
NAME = 
PATH_GATEKEEPER = Farm@Fortress 1
PATH_POINTS = 
Engine.MoveTo(31032, 74312, -3776, 90);
Engine.MoveTo(32312, 74008, -3736, 90);
Engine.MoveTo(34072, 73752, -3608, 90); base
Engine.MoveTo(35240, 73688, -3576, 60);


[SPOT 22]
TAG = FARM
NAME = 
PATH_GATEKEEPER = Farm@Fortress 1
PATH_POINTS = 
Engine.MoveTo(31032, 74312, -3776, 90);
Engine.MoveTo(32312, 74008, -3736, 90);
Engine.MoveTo(34072, 73752, -3608, 90); base
Engine.MoveTo(34360, 72104, -3480, 60);




-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------






-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------
