[COMMON]
SERVER_NAME = now_golden_main

; Adicionar/Disminuir horas para igualar el horario del servidor GMT-3
; Si es el mismo horario dejar vacio.
SERVER_TIME_DIFF = 1h

BUFFER_ID = 50001
GATEKEEPER_ID = 50008
MASTER_CLASS_ID = 50006

USE_BUFFER_BOOK = false
BUFFER_BOOK_ID = 13024


MODE_FARM = true
MODE_EVENT = true


NPC_SUBCLASS_PATH = Sub Class@Change subclass.

GM_NICKS = Admin@[ADM]@[GM]
SU_NICKS = Roma

USE_DEBUG_MSG = true

USE_F12_ACTIVE_ANTICHEAT = true

USE_SOUND_EVENT_REGISTER = true

; Engine.SetTarget o el otro metodo mas rapido.
USE_SET_TARGET = false

; Las notificaciones solo se envian a uno de los servicio de mensajeria: Telegram o Discord
TELEGRAM_API = aa4c396fce350285f51ea14ddc805118


[AUTOLOGIN]
USE_AUTOLOGIN = false
PATH_L2_EXE = C:\L2\L2COVEN\system\l2.exe
LOGIN_USER = 
LOGIN_PASS = 
CHAR_INDEX = 0


[HUNTER_PK]
USE_HUNTER_PK = false
HUNTER_WHITELIST_CLAN = 
HUNTER_WHITELIST_NICK = 
; opcional / use one key like F1, F2, 1, 2, q, w
HUNTER_PICKUP_KEY = F7
HUNTER_RADIO = 1800


[AUTOFARM]
VOICED_MENU = voiced_menu
VOICED_AUTOFARM = voiced_farm

VOICED_AUTOFARM_ON = bp_autofarm_toggle
VOICED_AUTOFARM_OFF = bp_autofarm_toggle

TEXT_AUTOFARM_ON = dema.panel.on
TEXT_AUTOFARM_OFF = dema.panel.off

VOICED_AUTOFARM_RANGE_DEC = bp_autofarm_dradius
VOICED_AUTOFARM_RANGE_INC = bp_autofarm_iradius

VOICED_AUTOFARM_PAGE_DEC = bp_autofarm_dshortcut
VOICED_AUTOFARM_PAGE_INC = bp_autofarm_ishortcut

; Ex. = 1200 1000 600, Disable = 0
AUTOFARM_RANGE = 1000
; Ex. = 10 1, Disable = 0
AUTOFARM_PAGE = 8
; GB
VOICED_SET_AUTO_GB = mod_menu_goldbar


TO_VILLAGE_DELAY = 10000
TO_VILLAGE_DELAY_EXTRA = 5000
; delay aplicado despues de dar click en To Village, es el tiempo que le toma aparecer en la city
TO_VILLAGE_AFTER = 2000

; delay em ms para volver a iniciar un farm.
FARM_AGAIN_DELAY = 5000
; delay random adicional al anterior.
FARM_AGAIN_DELAY_EXTRA = 5000

; Apply this RANDOM DELAY in SECONDS after events like PvP/Tour/SoloBoss and TvT/Ktb/Ctf/Fos
AFTER_EVENT_DELAY_SEC = 20

; numero de veces que ira  farmear 
NUMERO_DE_CICLOS = 99999   

USE_SERVER_AUTOFARM = true
USE_ADRENALINE_AUTOFARM = false
USE_MY_AUTOFARM = false


[TELEPORT_SETTINGS]
; use bypass for dialogs
USE_BYPASS = true

USE_EXECUTE_BYPASS = false

; use Alt+B
USE_ALT_B = false

; stugart
TP_AUX_BYPASS =

; use book for teleport ?
USE_BOOK_ITEM = false
BOOK_ID = 5588

; Use other city for start, this help for evade stuck in giran.
USE_PROXY_CITY = false
USE_PROXY_ONLY_FOR_BUFF = true
PROXY_PATH = Towns@Dion

; To Village / To Clan hall
USE_TO_CLAN_HALL = false
; rtTown, rtClanHall, rtCastle, rtFort, rtFlags
RES_TYPE = rtTown

; soe
USE_SCROLL_OF_SCAPE_CLAN_HALL = false
SCROLL_OF_SCAPE_CLAN_HALL_ID = 1829

USE_SCROLL_OF_SCAPE_GIRAN = true
SCROLL_OF_SCAPE_GIRAN_ID = 7126

USE_SCROLL_OF_SCAPE = false
SCROLL_OF_SCAPE_ID = 736

USE_UNSTUCK = false

SOE_EXTRA_DELAY = 8

USE_SOE_AFTER_DEAD = false


[FARM_SETTINGS]
; determina el spot para iniciar (20 parametros)
START_SPOT = 1
; muertes por spot
DEATHS_BY_SPOT = 1

; arcane power / vicous stance
USE_ARCANE_POWER = true

USE_MP_POTION = true
MP_POTION_NAME = Mana Potion
MP_POTION_PERCENTAGE = 65

USE_HP_POTION = true
HP_POTION_NAME = Major Healing Potion
HP_POTION_PERCENTAGE = 90

USE_CP_POTION = false
CP_POTION_NAME = Greater CP Potion
CP_POTION_PERCENTAGE = 85


; ONE_TIME_BYPASS = voiced_enableAntiKs@voiced_setBuffPrevent@voiced_LAssassin
; ONE_TIME_BYPASS = voiced_autofarm@[+]voiced_enableAntiKs@[+]enableSummonAttack
; ONE_TIME_BYPASS = voiced_menu@[+]voiced_hideEnchantGlow@[+]voiced_hideSkinsTextures@[+]voiced_hideWpSkinsTextures
; ONE_TIME_BYPASS = voiced_setPage 10@[+]voiced_enableAntiKs@[+]voiced_setTargetMode MONSTERS@[+]voiced_setTargetRange SHORT
ONE_TIME_BYPASS = 

; Show/Hide window options
; HIDE the window AFTER login
HIDE_GAME_WINDOW = false
; SHOW window to make To Village, then HIDE again.
SHOW_GAME_WINDOW_FOR_TO_VILLAGE = false

; Use when only can farm with 1 HWID
; When first char take 1 spot, the secondary char will be close cliente.
; use secondary char with objetive kill bots/chars/cleanSpots or farm quest quest
USE_DUALBOX_RESET = false
; Nick in Account list of adrenaline. the client will be force-close.
DUALBOX_RESET_NICK = 
DUALBOX_RESET_USE_SOE = false
DUALBOX_RESET_USE_GAMECLOSE = false


-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[TVT]
TVT = true
TVT_COMMAND = .tvtjoin

; Team vs Team: Teleport in x second(s)
TVT_TELEPORT_IN = 5

; Team vs Team: Fight start in x second(s)
TVT_EVENT_START_IN = 10

; x second(s) until the event is finished
TVT_EVENT_FINISH_IN = 290
; Teleporting back to town in x second(s)
TVT_TELEPORT_BACK_TO_TOWN_IN = 25

TVT_USE_TARGET_ATTACKABLE = false

; line
TVT_USE_TARGET_LINE_AB = true
TVT_LINE_AB_POINTS = 
tvt.baium.lineAB(115784, 14328, 10080);
tvt.baium.lineAB(113384, 17832, 10072);
tvt.bandit.lineAB(83160, -17720, -1824);
tvt.bandit.lineAB(83352, -15080, -1824);
now.ctf.line(7232, 149559, -2894);
now.ctf.line(4520, 149272, -2888);
now.tvt.tezza.line(175911, -87997, -5111);
now.tvt.tezza.line(172530, -87998, -5111);
Engine.MoveTo(149410, 45475, -3415);
Engine.MoveTo(149466, 47970, -3415);


; autofarm
TVT_USE_SERVER_AUTOFARM = false
TVT_AUTOFARM_BYPASSES = 

; teams
TVT_USE_TARGET_NAME = false
TVT_USE_TARGET_TITLE = false

TVT_MESSAGES_REGISTRATION_FIRST = TvT Event@reg@5 minute
TVT_MESSAGES_REGISTRATION = TvT Event@reg
TVT_MESSAGES_START = TvT Event@reg@ 5 second

TVT_METHOD = V3


; Mutiples coordenadas xyz
TVT_EVENT_CENTER = 
tvt.baium.center(114504, 15960, 10080);
tvt.bandit.center(83112, -16552, -1888);
now.ctf.center(4660, 149528, -2894);
now.tvt.tezza.center(174248, -88041, -5117);
Engine.MoveTo(149391, 46867, -3415);




-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[KTB]
KTB = true

KTB_COMMAND = .join

KTB_RAID_XYZ = Engine.MoveTo(29450, 75139, -3780);

; Teleporting in x second(s)
KTB_TELEPORT_IN = 15

; [Kill The Boss] Boss spawn in x second(s)
KTB_EVENT_START_IN = 5

; Teleporting back to town in x second(s)
KTB_TELEPORT_BACK_TO_TOWN_IN = 30

; Registrations for event: KTB have been opened
KTB_MESSAGES_REGISTRATION_FIRST = Boss Event@reg@5 minute
KTB_MESSAGES_REGISTRATION = Boss Event@reg
KTB_MESSAGES_START = Boss Event@reg@ 5 second

Engine.SetTarget(29020);   // Baium[id: 29020]   
  


-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[CTF]
CTF = true
CTF_COMMAND = .ctfjoin
CTF_TELEPORT_IN = 5
CTF_EVENT_START_IN = 10
CTF_EVENT_FINISH_IN = 290
CTF_TELEPORT_BACK_TO_TOWN_IN = 20
CTF_MESSAGES_REGISTRATION = CTF Event@reg
CTF_MESSAGES_START = CTF Event@reg@ 5 second


[FOS]
FOS = true
FOS_COMMAND = .fortressjoin
FOS_TELEPORT_IN = 5
FOS_EVENT_START_IN = 10
FOS_EVENT_FINISH_IN = 290
FOS_TELEPORT_BACK_TO_TOWN_IN = 20
FOS_MESSAGES_REGISTRATION = Fortress Event@reg@5 minute
FOS_MESSAGES_START = Fortress Event@reg@ 5 second


-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[SOLO BOSS]
SOLO_BOSS = true
SOLO_BOSS_TELEPORT_PATH = Solo Boss

SOLO_BOSS_DEFAULT_BEFORE = 4m
SOLO_BOSS_DEFAULT_END = 2m

; la hora en que nace el primer raid solo 
;{start|before|end}
SOLO_BOSS_SCHEDULE = 10:50 @ 17:35 @ 21:05

;{ Solo boss path for each raid }
SOLO_BOSS_PATH_1 = now.solo.boss(-76401, 92828, -3717, 180);
SOLO_BOSS_PATH_2 = now.solo.boss(-75452, 91593, -3633, 180);
SOLO_BOSS_PATH_3 = now.solo.boss(-72324, 93452, -3651, 180);
SOLO_BOSS_PATH_4 = now.solo.boss(-73358, 96249, -3715, 180);

SOLO_BOSS_PATH_5 = now.solo.boss(-71142, 98232, -3714, 180);
SOLO_BOSS_PATH_6 = 
SOLO_BOSS_PATH_7 = 
SOLO_BOSS_PATH_8 = 

SOLO_BOSS_PATH_9 = 
SOLO_BOSS_PATH_10 =

SOLO_BOSS_USE_PICKUP = false

; When have many NPC near, can set the NPC ID (@ separator)
SOLO_BOSS_NPC_IDS = 25282@25126@25281@29065@25276

; chest ID after raid dead
SOLO_BOSS_CHEST_ID = 




-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[PVP]
PVP_EVENT = true

PVP_EVENT_USE_CP = true
PVP_EVENT_CENTERS = 
pi(9310, -23131, -3706, 15000, 1500); 


; 103 sps / 94 Archmage / 95 soultaker / 110 storm screamer
; 113 titan / 114 gk / 88 duelist / 
; 92 sagi / 93 adventurer
; PVP_EVENT_CLASS_ID = 102
PVP_EVENT_CLASS_ID = 95

PVP_EVENT_TELEPORT_PATH = PvP Zone

PVP_EVENT_DEFAULT_BEFORE = 1m 20s
PVP_EVENT_DEFAULT_END = 30m

;{start|before|end}
PVP_EVENT_SCHEDULE = 12:15 @ 16:15 @ 19:15 @ 00:15

PVP_EVENT_USE_GK_TO_LEAVE_ZONE = false

; use for mage/archer
PVP_USE_MOVE_SPAWN = true
PVP_MOVE_SPAWN_DIST = 300
PVP_MOVE_SPAWN_TIME_MS = 1400

; extra delay for to village, default 0
PVP_TO_VILLAGE_EXTRA_DELAY_SECONDS = 0

PVP_AGGRESSIVE_PLAYERS_FIRST = false
; avoid targeting the following classes (@ separator)
PVP_IGNORE_CLASSES = 88

; rtTown, rtClanHall, rtCastle, rtFort, rtFlags
PVP_RES_TYPE = rtTown
PVP_RES_TYPE_LEAVE_ZONE = rtFlags
PVP_USE_NOBLESSE = false
PVP_NO_ACTIVITY_COMMANDS = 

; tyrant: puma @ ogre @ hawk @ bear @ soul breaker @ force burst @ force blaster
; sps: solar @ ice vortex @ light vortex
; PVP_SKILL_LIST = hawk @ soul breaker @ force burst 
; PVP_SKILL_LIST = hawk @ force burst 
; PVP_SKILL_LIST = bear @ force burst @ force storm @ force blaster @ burning fist @ soul breaker
PVP_SKILL_LIST = surrender @ solar flare

; autofarm
PVP_USE_SERVER_AUTOFARM = false
PVP_AUTOFARM_BYPASSES = voiced_enableAutoAttack@voiced_enableAutoTarget@voiced_setTargetMode PLAYERS@voiced_setTargetRange LONG

PVP_ZMAP =

PVP_USE_ADD_FRIEND = false
PVP_OID_FRIENDS = 





-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[TOUR]
TOUR_EVENT = true
TOUR_EVENT_CENTER = now.tour(-120469, -225222, -3334);

TOUR_EVENT_RANGE = 3000
TOUR_EVENT_ZLIMIT = 250

TOUR_EVENT_NPC_ID = 32027

TOUR_REGISTER_PATH = Tournament Arenas@T1V1@Register
TOUR_UNREGISTER_PATH = remove

; 93 adventurer; 94 sorcer  103 sps
; 114 GK / 88 duelist
TOUR_CLASS_ID = 95
TOUR_EVENT_TELEPORT_PATH = Tournament Zone

TOUR_EVENT_DEFAULT_BEFORE = 1s
TOUR_EVENT_DEFAULT_END = 30m

;start|before|end
TOUR_EVENT_SCHEDULE = 11:15 @ 14:15 @ 22:50

TOUR_USE_SUMMON_CP = false

; if have agation or pet
TOUR_HAVE_AGATION_PET = true




-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[EVENT ZONE A]
USE = false
TAG = RUSH
DEFAULT_BEFORE = 20s
DEFAULT_END = 15m
USE_SERVER_TIME = true
SCHEDULE = 01:35 @ 03:35 

[EVENT ZONE B]
USE = false
TAG = AOE
DEFAULT_BEFORE = 1s
DEFAULT_END = 30m
USE_SERVER_TIME = true
SCHEDULE = 0:25


[EVENT ZONE C]
USE = false
TAG = ZONE3
DEFAULT_BEFORE = 40s
DEFAULT_END = 2m 30s
USE_SERVER_TIME = true
SCHEDULE = 20:05

[EVENT ZONE D]
USE = false
TAG = DUNGEON
DEFAULT_BEFORE = 10s
DEFAULT_END = 45m
USE_SERVER_TIME = true
SCHEDULE = 2:00

[EVENT ZONE E]
USE = false
TAG = DUNGEON
DEFAULT_BEFORE = 1s
DEFAULT_END = 30m 30s
USE_SERVER_TIME = true
SCHEDULE = 9:10 @ 11:10 @ 16:10 @ 18:10 @ 22:10 @ 1:10



-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[MISSION]
MISSION = false
MISSION_VOICED = voiced_mission
MISSION_COMPLETED_TEXT_1 = <font color="00FF00">
MISSION_COMPLETED_TEXT_2 = >Completed<
MISSION_LIST_VOICED = voiced_tvt_mission@voiced_tvt_mission_reward


-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[SUBCLASS 1]
CLASS_ID = 103
CLASS_NAME = Mystic Muse
BUFF_PATH = *@mage@Special@Prophecies@water
ITEMS_SKILL = 
ARRAY_EQUIPMENT_ID = 
USE_LOAD_GEAR = false

[SUBCLASS 2]
CLASS_ID = 95
CLASS_NAME = Soultaker
BUFF_PATH = *@mage
ITEMS_SKILL = 
ARRAY_EQUIPMENT_ID = 
USE_LOAD_GEAR = false

[SUBCLASS 3]
CLASS_ID = 110
CLASS_NAME = Storm Screamer
BUFF_PATH = *@Wizard
ITEMS_SKILL = 
ARRAY_EQUIPMENT_ID =
USE_LOAD_GEAR = false



[SUBCLASS 4]
CLASS_ID = 93
CLASS_NAME = Adventurer
BUFF_PATH = *@Scheme@Dagger@*@Restore
ITEMS_SKILL = 
ARRAY_EQUIPMENT_ID =
USE_LOAD_GEAR = false

[SUBCLASS 5]
CLASS_ID = 113
CLASS_NAME = Titan
BUFF_PATH = *@Cancel@Scheme@Titan@*
ITEMS_SKILL = 
ARRAY_EQUIPMENT_ID =
USE_LOAD_GEAR = false

[SUBCLASS 6]
CLASS_ID = 88
CLASS_NAME = Duelist
BUFF_PATH = *@Scheme@duelist@*@Restore
ITEMS_SKILL =
ARRAY_EQUIPMENT_ID = 6580
USE_LOAD_GEAR = false

[SUBCLASS 7]
CLASS_ID = 114
CLASS_NAME = Grand Khauatari
BUFF_PATH = *@Scheme@GK@*@Restore
ITEMS_SKILL = 10527
ARRAY_EQUIPMENT_ID = 6602
; ARRAY_EQUIPMENT_ID = 6603
USE_LOAD_GEAR = false

[SUBCLASS 8]
CLASS_ID = 92
CLASS_NAME = Sagittarius
BUFF_PATH = *@Warrior@Song@Renewal
ITEMS_SKILL = 10527
ARRAY_EQUIPMENT_ID = 7577
USE_LOAD_GEAR = false


[SUBCLASS 9]
CLASS_ID = 102
CLASS_NAME = Moonlight Sentinel
BUFF_PATH = *@Warrior@Song@Renewal
ITEMS_SKILL = 10527
ARRAY_EQUIPMENT_ID = 7577
USE_LOAD_GEAR = false

[SUBCLASS 10]
[SUBCLASS 11]
[SUBCLASS 12]






-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

[SPOT DEFAULT]
TAG = DEFAULT
NAME = (default)
SUBCLASS_ID = 95
FORCE_REBUFF = true
BACK_TO_LAST_POSITION = true
BACK_TO_POSITION_RANGE = 200
USE_CHAR_PARADO = true
EXTRA_BYPASS = 

AUTOFARM_RANGE = 1000
AUTOFARM_PAGE = 8

USE_FAST_SKILL = true
FAST_SKILL_DELAY_MS = 150

USE_SURRENDER = false
USE_CORPSE_LIFE_DRAIN = false
USE_AOE = false
USE_PET = false
BTM_FROM_HP = 500
USE_REPEAT_TP = false

; pathGatekeeper = 
; pathPoints = 

USE_GPS = false
GPS_FILENAME = 

; MyAutoFarm Settings
USE_HUNT_PLAYER_PVP = false
HUNT_RADIO = 1200

USE_PROTECT_FROM_PVP_PK = false


COMMANDS_BEFORE_BUFF = 
COMMANDS_AFTER_BUFF = 


-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

; Lake 1
; Lake 2

; Fortress I
; Fortress II


; How to create SPOTS
; https://youtu.be/hh_ua0NzCIg?si=cFdvPsLkxKoU1xyz

-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------



[SPOT 3]
TAG = FARM
NAME = Iris Random
PATH_GATEKEEPER = Farm@Iris Random Spot
PATH_POINTS = Set.By.Script.for.option.IGNORE_PATH_POINTS(55654,88796,-3472); 
IGNORE_PATH_POINTS = true


[SPOT 4]
TAG = FARM
NAME = Fortress Random
PATH_GATEKEEPER = Farm@Fortress Random Spot
PATH_POINTS = Set.By.Script.for.option.IGNORE_PATH_POINTS(37976,74720,-3626); 
IGNORE_PATH_POINTS = true



-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------


[SOLO RAID DEFAULT]
SUBCLASS_ID = 95

KEYS_SEQUENCE_BEFORE_BUFF = 6@7
KEYS_SEQUENCE_AFTER_BUFF = 6@1

KEYS_SEQUENCE_BEFORE_TP = 
KEYS_SEQUENCE_AFTER_TP = 2@3@4

KEYS_SEQUENCE_AFTER_RAID_PATH = 

DEFAULT_BEFORE = 1m 
DEFAULT_END = 1m
USE_SERVER_TIME = true

USE_DAMAGE = false
USE_PICK_UP = false

MESSAGES_SCHEDULE_15m = Announcements@will appear in @15 minute
MESSAGES_SCHEDULE_10m = Announcements@will appear in @10 minute
MESSAGES_SCHEDULE_5m  = Announcements@will appear in @5 minute
MESSAGES_SCHEDULE_3m  = Announcements@will appear in @3 minute




[SOLO RAID 2]
USE = true
NAME = Splendor Barakiel
RAID_ID = 
SCHEDULE = 05:00:00
TELEPORT_PATH = Raid@Barakiel
RAID_PATH = Engine.MoveTo(91448, -86072, -2712, 100);